import type {Metadata, Viewport} from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Undo } from "@/components/Undo/Undo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <script
          dangerouslySetInnerHTML={{
              __html: `(() => {\n` +
                  `  try {\n` +
                  `    const t = localStorage.getItem('theme');\n` +
                  `    if (t === 'dark') {\n` +
                  `      document.documentElement.classList.add('dark');\n` +
                  `    } else {\n` +
                  `      document.documentElement.classList.remove('dark');\n` +
                  `    }\n` +
                  `  } catch (e) {}\n` +
                  `})()`
          }}
      />
    <Undo>{children}</Undo>
      </body>
    </html>
  );
}
